{% set version = "0.8.96" %}

package:
  name: ensmallen_graph
  version: {{ version }}

source:
  # There's no github tag, but this is the commit used for PyPI publishing
  # See https://github.com/AnacletoLAB/ensmallen/issues/226
  url: https://github.com/AnacletoLAB/ensmallen/archive/b2492e02dfdb9a7a10ca087d53b3207aadca3b9c.tar.gz
  sha256: 044e1ac0cd53f1ec39744f7984a341e27a6c7a80850e3d23934ff2a41e8159c4
  patches:
    - 0001-No-zig.patch
    - 0001-Use-thin-lto.patch

build:
  script:
    - cd bindings/python
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
    - {{ PYTHON }} ./build.py --skip-repair
    - {{ PYTHON }} -m pip install wheels/*.whl
  number: 0
  skip: True  # [not linux64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin
    - pip
  run:
    - python
    - toml >=0.10.0
    - downloaders >=1.0.15
    - compress_json >=1.0.7
    - userinput >=1.0.19
    - cache_decorator >=2.1.11
    - bioregistry >=0.5.65
    - tqdm
    - pandas
    - py-cpuinfo
    - environments_utils >=1.0.13

test:
  imports:
    - ensmallen
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AnacletoLAB/ensmallen
  summary: Ensmallen is the Rust/Python high-performance graph processing submodule of the GRAPE library.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
